name: flutter_shaders
description: A collection of utilities for working with the FragmentProgram API in Flutter.
repository: https://github.com/jonahwilliams/flutter_shaders
issue_tracker: https://github.com/jonahwilliams/flutter_shaders/issues
version: 0.1.1

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.7.0-0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
